plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.jfoenix:jfoenix:9.0.10'  // Versión para JavaFX 11+
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'org.k3p.speedtest.SpeedTestApp'
}

jar {
    manifest {
        attributes(
                'Main-Class': application.mainClass
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

javafx {
    version = "21"  // Usa la última versión estable
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
